<#
.SYNOPSIS
    Installs (or updates) the "OLT-Optical-Monitor" Windows Scheduled Task.

.DESCRIPTION
    Creates a scheduled task that runs `python.exe monitor.py run` every 20
    minutes, starting 2 minutes from now, repeated indefinitely. The task runs
    only when the current user is logged on (no stored password required) and
    runs without elevation.

    Implementation choice for stdout/stderr redirection:
        We write a small helper batch file `run.cmd` next to monitor.py and
        configure the scheduled task action to invoke that batch file. This
        keeps the redirection logic out of the task XML (where quoting `>>`
        and `2>&1` is awkward) and makes it trivial for the user to test the
        same command interactively. The batch file appends a timestamp banner
        and then runs python with both streams redirected to monitor.log.

.HOW TO RUN
    Right-click the .ps1 -> "Run with PowerShell", or from a terminal:
        powershell -ExecutionPolicy Bypass -File install_task.ps1

.HOW TO REMOVE
    Unregister-ScheduledTask -TaskName 'OLT-Optical-Monitor' -Confirm:$false

.LOG FILE
    c:\Users\Manuel\Documents\GitHub\informacion\centinela_work\olt_monitor\monitor.log
#>

[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

# ----- Paths -----
$TaskName    = 'OLT-Optical-Monitor'
$ScriptDir   = 'c:\Users\Manuel\Documents\GitHub\informacion\centinela_work\olt_monitor'
$MonitorPy   = Join-Path $ScriptDir 'monitor.py'
$LogFile     = Join-Path $ScriptDir 'monitor.log'
$RunCmd      = Join-Path $ScriptDir 'run.cmd'

if (-not (Test-Path -LiteralPath $MonitorPy)) {
    throw "monitor.py not found at: $MonitorPy"
}

# ----- Locate a Python interpreter -----
function Resolve-PythonLauncher {
    # Try `python.exe` on PATH.
    $py = Get-Command -Name 'python.exe' -ErrorAction SilentlyContinue
    if ($py) {
        return @{ Exe = $py.Source; Args = '' }
    }
    # Try `py -3` (the PEP 397 launcher).
    $pyLauncher = Get-Command -Name 'py.exe' -ErrorAction SilentlyContinue
    if ($pyLauncher) {
        return @{ Exe = $pyLauncher.Source; Args = '-3' }
    }
    throw "Could not find python.exe or py.exe on PATH. Install Python from https://www.python.org/ and re-run, or edit this script to hard-code the interpreter path."
}

$python = Resolve-PythonLauncher
Write-Host "Using Python interpreter: $($python.Exe) $($python.Args)" -ForegroundColor Cyan

# ----- Write the helper batch file (run.cmd) -----
# Note: %date% / %time% locale-vary; we use PowerShell-style timestamp via a
# small inline call to avoid locale headaches.
$cmdLines = @(
    '@echo off',
    'REM Auto-generated by install_task.ps1 — do not edit by hand; re-run the installer instead.',
    "cd /d ""$ScriptDir""",
    "for /f ""usebackq tokens=*"" %%T in (`powershell -NoProfile -Command ""Get-Date -Format 'yyyy-MM-dd HH:mm:ss'""`) do set NOW=%%T",
    "echo ===== %NOW% ===== >> ""$LogFile""",
    ('"{0}" {1} "{2}" run >> "{3}" 2>&1' -f $python.Exe, $python.Args, $MonitorPy, $LogFile)
)
Set-Content -LiteralPath $RunCmd -Value $cmdLines -Encoding ASCII
Write-Host "Wrote helper batch: $RunCmd" -ForegroundColor Cyan

# ----- Build scheduled task pieces -----
$action = New-ScheduledTaskAction -Execute $RunCmd -WorkingDirectory $ScriptDir

$startTime = (Get-Date).AddMinutes(2)
$trigger   = New-ScheduledTaskTrigger -Once -At $startTime `
              -RepetitionInterval (New-TimeSpan -Minutes 20)

# Run as the current interactive user, only when logged on, no elevation.
$principal = New-ScheduledTaskPrincipal `
                -UserId ([System.Security.Principal.WindowsIdentity]::GetCurrent().Name) `
                -LogonType Interactive `
                -RunLevel Limited

$settings = New-ScheduledTaskSettingsSet `
                -MultipleInstances IgnoreNew `
                -AllowStartIfOnBatteries `
                -DontStopIfGoingOnBatteries `
                -StartWhenAvailable

# ----- Register or update the task (idempotent) -----
$existing = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
if ($existing) {
    Write-Host "Existing task found; removing before re-registering..." -ForegroundColor Yellow
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
}

Register-ScheduledTask `
    -TaskName  $TaskName `
    -Action    $action `
    -Trigger   $trigger `
    -Principal $principal `
    -Settings  $settings `
    -Description 'Polls OLT optical levels every 20 minutes (monitor.py run).' | Out-Null

# ----- Summary -----
$task = Get-ScheduledTask -TaskName $TaskName
$info = $task | Get-ScheduledTaskInfo

Write-Host ''
Write-Host '================ OLT Monitor scheduled task installed ================' -ForegroundColor Green
Write-Host ("  Task name     : {0}" -f $TaskName)
Write-Host ("  Next run time : {0}" -f $info.NextRunTime)
Write-Host ("  Log file      : {0}" -f $LogFile)
Write-Host ("  Helper script : {0}" -f $RunCmd)
Write-Host '======================================================================' -ForegroundColor Green
Write-Host ''
Write-Host "To remove:  Unregister-ScheduledTask -TaskName '$TaskName' -Confirm:`$false"
