#!/usr/bin/env python3
"""Parse an M3U file and emit SQL to bulk-load streams into XUI.

Streams are organized by category: one independent transaction per category,
so a single bad row never rolls back the whole load. Each entry becomes one
live stream (type=1) with `on_demand=1` (XUI starts ffmpeg only on client
request), linked to the main server (id=1) via streams_servers.
"""

import json
import re
import sys
import time
import uuid
from collections import defaultdict
from pathlib import Path

M3U_PATH = Path(sys.argv[1] if len(sys.argv) > 1 else "ec387860_lista.m3u")
SQL_PATH = Path(sys.argv[2] if len(sys.argv) > 2 else "xui_load.sql")
SERVER_ID = 1
ON_DEMAND = 1   # 1 = ffmpeg arranca solo cuando el cliente pide el stream

ATTR_RE = re.compile(r'([a-zA-Z0-9\-]+)="([^"]*)"')


def parse_m3u(path):
    """Yield (group, name, logo, url) tuples in M3U order."""
    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    i = 0
    while i < len(lines):
        line = lines[i].strip()
        if line.startswith("#EXTINF"):
            attrs = dict(ATTR_RE.findall(line))
            comma = line.rfind(",")
            name = line[comma + 1:].strip() if comma != -1 else ""
            group = attrs.get("group-title", "Sin categoria").strip() or "Sin categoria"
            logo = attrs.get("tvg-logo", "").strip()
            url = ""
            for j in range(i + 1, min(i + 5, len(lines))):
                cand = lines[j].strip()
                if cand and not cand.startswith("#"):
                    url = cand
                    i = j
                    break
            if url:
                yield group, name, logo, url
        i += 1


def sql_str(s):
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'") + "'"


def main():
    entries = list(parse_m3u(M3U_PATH))
    print(f"Parsed {len(entries)} streams", file=sys.stderr)

    # Group entries by category, preserving first-seen order of categories
    cats_order = []
    by_cat = defaultdict(list)
    for entry in entries:
        group = entry[0]
        if group not in by_cat:
            cats_order.append(group)
        by_cat[group].append(entry)
    print(f"Found {len(cats_order)} categories", file=sys.stderr)

    now = int(time.time())
    out = []
    out.append("-- Generated by m3u_to_xui.py")
    out.append(f"-- Source: {M3U_PATH.name}")
    out.append(f"-- Categories: {len(cats_order)}  Streams: {len(entries)}")
    out.append("-- One transaction per category. A failure in one category does not")
    out.append("-- roll back the others.")
    out.append("SET NAMES utf8mb4;")
    out.append("")

    for idx, category in enumerate(cats_order, 1):
        rows = by_cat[category]
        out.append(f"-- ===== Category {idx}/{len(cats_order)}: {category}  ({len(rows)} streams) =====")
        out.append("START TRANSACTION;")
        out.append(
            "INSERT INTO streams_categories "
            "(category_type, category_name, parent_id, cat_order, is_adult) VALUES "
            f"('live', {sql_str(category)}, 0, 99, 0);"
        )
        out.append("SET @cat := LAST_INSERT_ID();")
        for _, name, logo, url in rows:
            source_json = json.dumps([url])
            uid = uuid.uuid4().hex
            out.append(
                "INSERT INTO streams "
                "(type, category_id, stream_display_name, stream_source, stream_icon, "
                "read_native, direct_source, `order`, added, uuid, rating) VALUES "
                f"(1, CONCAT('[', @cat, ']'), {sql_str(name)}, {sql_str(source_json)}, "
                f"{sql_str(logo)}, 1, 0, 0, {now}, '{uid}', 0);"
            )
            out.append(
                "INSERT INTO streams_servers (stream_id, server_id, on_demand, stream_status) "
                f"VALUES (LAST_INSERT_ID(), {SERVER_ID}, {ON_DEMAND}, 0);"
            )
        out.append("COMMIT;")
        out.append("")

    out.append("-- Verification queries")
    out.append("SELECT COUNT(*) AS total_streams FROM streams WHERE type=1;")
    out.append("SELECT COUNT(*) AS total_categories FROM streams_categories WHERE category_type='live';")

    SQL_PATH.write_text("\n".join(out), encoding="utf-8")
    print(f"Wrote {SQL_PATH} ({SQL_PATH.stat().st_size} bytes)", file=sys.stderr)
    print(f"Streams: {len(entries)}  Categories: {len(cats_order)}  Transactions: {len(cats_order)}", file=sys.stderr)


if __name__ == "__main__":
    main()
